ARG ALPINE_VERSION=3.18
FROM alpine:${ALPINE_VERSION}
LABEL Maintainer="Ondrej Sotek <ondrej.sotek@eclair.cz>"
LABEL Description="PHP 7.4"
# Setup document root
WORKDIR /var/www/html

ENV DEBUG_MODE=1
ENV PHP_MEMORY_LIMIT=512M
ENV PHP_UPLOAD_MAX_FILESIZE=50M
ENV PHP_POST_MAX_SIZE=100M
ENV PHP_MAX_EXECUTION_TIME=300

# Inspired by https://github.com/EvilFreelancer/alpine-apache-php82/tree/master

# Install packages and remove default server definition
RUN apk add --no-cache \
    curl \
    apache2 php82-apache2 php82 \
    php82-json \
    php82-iconv \
    php82-ftp \
    php82-soap \
    php82-gmp \
    php82-dom \
    php82-pdo \
    php82-zip \
    php82-mysqli \
    php82-gd \
    php82-pdo_mysql \
    php82-gettext \
    php82-xml \
    php82-xmlreader \
    php82-bz2 \
    php82-curl \
    php82-ctype \
    php82-exif \
    php82-session \
    php82-openssl \
    php82-phar \
    php82-tokenizer \
    php82-simplexml \
    php82-pdo_sqlite \
    php82-sqlite3 \
    php82-intl \
    php82-fileinfo \
    php82-xmlwriter 

# Install composer
RUN curl -sS https://getcomposer.org/installer | /usr/bin/php82 && mv composer.phar /usr/local/bin/composer

# Add apache to run and configure
RUN mkdir -p /run/apache2 \
 && sed -i "s/#LoadModule\ rewrite_module/LoadModule\ rewrite_module/" /etc/apache2/httpd.conf \
 && sed -i "s/#LoadModule\ session_module/LoadModule\ session_module/" /etc/apache2/httpd.conf \
 && sed -i "s/#LoadModule\ session_cookie_module/LoadModule\ session_cookie_module/" /etc/apache2/httpd.conf \
 && sed -i "s/#LoadModule\ session_crypto_module/LoadModule\ session_crypto_module/" /etc/apache2/httpd.conf \
 && sed -i "s/#LoadModule\ deflate_module/LoadModule\ deflate_module/" /etc/apache2/httpd.conf \
 && sed -i "s#^DocumentRoot \".*#DocumentRoot \"/var/www/html/public\"#g" /etc/apache2/httpd.conf \
 && sed -i "s#/var/www/localhost/public#/var/www/html/public#" /etc/apache2/httpd.conf \
 && printf "\n<Directory \"/var/www/html/public\">\n\tAllowOverride All\n</Directory>\n" >> /etc/apache2/httpd.conf

RUN mkdir -p /var/www/html/public \
 && chown -R apache:apache /var/www/html \
 && chmod -R 755 /var/www/html
 
# COPY /usr/share/zoneinfo/Europe/Prague /etc/localtime
# RUN echo "Europe/Prague" > /etc/timezone

# PHP config
RUN sed -i "s/\;\?\\s\?memory_limit = .*/memory_limit = $PHP_MEMORY_LIMIT/" /etc/php82/php.ini
RUN sed -i "s/\;\?\\s\?upload_max_filesize = .*/upload_max_filesize = $PHP_UPLOAD_MAX_FILESIZE/" /etc/php82/php.ini
RUN sed -i "s/\;\?\\s\?post_max_size = .*/post_max_size = $PHP_POST_MAX_SIZE/" /etc/php82/php.ini
RUN sed -i "s/\;\?\\s\?max_execution_time = .*/max_execution_time = $PHP_MAX_EXECUTION_TIME/" /etc/php82/php.ini


# Expose the port nginx is reachable on
EXPOSE 80

RUN rm -f /run/apache2/apache2.pid
RUN rm -f /run/apache2/httpd.pid

# Symlink php to php82
RUN ln -s /usr/bin/php82 /usr/bin/php

# Start apache
CMD ["httpd","-D","FOREGROUND"]

